# Generated by Django 3.2 on 2021-05-15 09:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210515_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 15, 9, 42, 10, 874901, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
